### ISSUE TITLE
오류

### ISSUE THREAD

**Issue by Chooonche** [NellLucas/classcard_hack#1]
학습할 세트 url을 입력하고 1번 즉 암기를 선택하고나서
크롬 드라이버를 불러옵니다 뜨고 오류가 납니다..

크롬드라이버를 설치중입니다!(Ver: 117)
WARNING:root:Can not find chromedriver for currently installed chrome version.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 97, in start
    path = SeleniumManager().driver_location(browser)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 74, in driver_location
    result = self.run((binary, flag, browser))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 93, in run
    raise SeleniumManagerException(f"Selenium manager failed for: {command}. {stderr}")
selenium.common.exceptions.SeleniumManagerException: Message: Selenium manager failed for: C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\classcard_hack-main\main.py", line 37, in <module>
    driver = webdriver.Chrome(driver_path, options=options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    super().__init__(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 103, in __init__
    self.service.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 100, in start
    raise err
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 90, in start
    self._start_process(self.path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 213, in _start_process
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

**Comment by Chooonche** [comment]
파이썬 3.9.7 사용중이구요 window 11입니다

**Comment by NellLucas** [comment]
Google이 최근 Chrome 및 ChromeDriver의 빌드 프로세스를 변경하여 Chrome 115 버전 이상부터 chromedriver_autoinstaller 모듈이 더 이상 작동하지 않습니다.  따라서, chromedriver_autoinstaller 관련 부분을 삭제하고 selenium 4.10 버전 이상부터 driver= webdriver.Chrome() 이렇게만 수정해도 작동하므로, 이에 맞게 코드를 수정하였습니다.
