### ISSUE TITLE
모든 학습 유형에서 오류 발생

### ISSUE THREAD

**Issue by DevNergis** [NellLucas/classcard_hack#3]
```
Traceback (most recent call last):
  File "C:\Users\sns77\PycharmProjects\classcard_hack\main.py", line 63, in <module>
    word_d = word_get(driver, num_d)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sns77\PycharmProjects\classcard_hack\utility.py", line 20, in word_get
    url = driver.find_element(By.XPATH, f"//*[@id='tab_set_all']/div[2]/div[{i}]/div[4]/div[1]/div[3]/a").get_attribute('data-src')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sns77\PycharmProjects\classcard_hack\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sns77\PycharmProjects\classcard_hack\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\sns77\PycharmProjects\classcard_hack\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='tab_set_all']/div[2]/div[1]/div[4]/div[1]/div[3]/a"}
  (Session info: chrome=126.0.6478.115); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6083A3E32+31618]
	(No symbol) [0x00007FF60831B099]
	(No symbol) [0x00007FF6081D888A]
	(No symbol) [0x00007FF608228524]
	(No symbol) [0x00007FF60822862C]
	(No symbol) [0x00007FF60826F787]
	(No symbol) [0x00007FF60824D14F]
	(No symbol) [0x00007FF60826CA80]
	(No symbol) [0x00007FF60824CEB3]
	(No symbol) [0x00007FF60821A46B]
	(No symbol) [0x00007FF60821B001]
	GetHandleVerifier [0x00007FF6086A9FFD+3202381]
	GetHandleVerifier [0x00007FF6086F6A1D+3516269]
	GetHandleVerifier [0x00007FF6086EC490+3473888]
	GetHandleVerifier [0x00007FF608455D36+760454]
	(No symbol) [0x00007FF608326B3F]
	(No symbol) [0x00007FF608321CD4]
	(No symbol) [0x00007FF608321E62]
	(No symbol) [0x00007FF60831120F]
	BaseThreadInitThunk [0x00007FFC9B49257D+29]
	RtlUserThreadStart [0x00007FFC9BE6AF28+40]
```

단어를 얻는 과정에서 오류가 발생 합니다.

**Comment by NellLucas** [comment]
작동 오류 해결 및 전체적인 코드 리팩터링을 거쳤습니다.

<feat & refactor: Adding API tampering features and overall code refactoring>

- feat: Add API request manipulation feature
- fix: Resolve incorrect HTML element access issue
- refactor: Code abstraction and modularization
- refactor: Comply with PEP 8 and use WebDriverWait()
